name: Autobuild on copr.
on:
  schedule:
    - cron: "14 3 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout repo
      uses: actions/checkout@v3
    
    - 
      name: Run update script
      run: ./update-slurm-packages.sh

        
