on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    - 
      name: Checkout repo
      uses: actions/checkout@v3
    
    - 
      name: Run update script
      run: ./update-slurm-packages.sh ${{ github.ref_name }}